const fs=require('fs'),path=require('path');const {pw,root,executablePath,gameURL}=require('./runtime.cjs');
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[],shots=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(gameURL);await p.waitForFunction(()=>V18M.ready&&V22T.ready&&V18UIR.bg('title'));await p.evaluate(()=>{startLevel();toTitle();_UPDATE=()=>{};SET.lang='zh';SET.touch='off';ST.debugActive=false;});const out=path.join(root,'docs/img/v1.10.0');fs.mkdirSync(out,{recursive:true});
async function snap(name,fn){await p.evaluate(fn);await p.evaluate(()=>{updOvl();draw(0);});await p.screenshot({path:path.join(out,name+'.jpg'),type:'jpeg',quality:90});shots.push(name);}
await snap('title',()=>toTitle());await snap('hulls',()=>openMenu('hull','title'));await snap('wingman',()=>openMenu('wingman','hull'));await snap('settings',()=>openMenu('option','title'));await snap('controls',()=>openMenu('controls','option'));
await p.evaluate(()=>{MENU=null;ST.state='upgrade';ST.upg={sel:0,from:'clear'};V18UIR.want('dep');});await p.waitForFunction(()=>V18UIR.bg('dep'));
await snap('refit',()=>{RUN=RUN_DEF();RUN.pts=12;RUN.up.hp=3;RUN.up.atk=2;MENU=null;ST.state='upgrade';ST.upg={sel:0,from:'clear'};});
await snap('help',()=>{openMenu('help','title');MENU.page=13;});
for(let lv=0;lv<7;lv++){await p.evaluate(lv=>{RUN=RUN_DEF();RUN.lvl=lv;RUN.hull=['assault','balanced','heavy'][lv%3];startLevel();ST.state='play';MENU=null;ST.introT=0;player.inv=0;SET.touch='off';AIART.fx.length=0;const px=player.x,py=player.y;for(const [dx,dy]of [[65,-48],[-75,-50],[115,15]])if(!blockedAt(px+dx,py+dy,13))spawnEnemyAt('tank',false,px+dx,py+dy);},lv);await snap('stage-'+(lv+1),()=>{});}
await snap('elite',()=>{RUN=RUN_DEF();RUN.hull='heavy';RUN.lvl=3;startLevel();MENU=null;ST.state='play';player.inv=0;spawnAce();const e=enemies[0];e.x=player.x+95;e.y=player.y-18;e.a=Math.PI;e.ta=Math.PI+.2;e.shieldT=1;e.shieldAge=.5;AIART.fx.length=0;});
await snap('formation',()=>{RUN=RUN_DEF();RUN.lvl=0;startLevel();MENU=null;ST.state='play';spawnFormation(6,'wedge');const g=ST.enc.group;cam.x=clamp(g.x-VW/2,0,WORLDW-VW);cam.y=clamp(g.y-VH/2,0,WORLDH-VH);cam.ox=cam.x;cam.oy=cam.y;AIART.fx.length=0;});
await snap('touch',()=>{RUN=RUN_DEF();RUN.lvl=0;startLevel();ST.state='play';MENU=null;player.inv=0;SET.touch='on';setAimMode('hybrid');setInMode('touch');AIART.fx.length=0;});
await snap('clear',()=>{SET.touch='off';pickups=[{kind:'part',val:3,x:player.x+85,y:player.y+10,t:20,bob:0}];levelClear();});
if(errors.length)throw new Error(errors.join('\n'));console.log(JSON.stringify({shots,errors}));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
