const fs=require('fs'),path=require('path'),pw=require('./runtime.cjs').pw;const root=path.resolve(__dirname,'../..'),out=require('./runtime.cjs').output('combat-20260905');
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:require('./runtime.cjs').executablePath});try{const p=await b.newPage({viewport:{width:960,height:540}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('./runtime.cjs').gameURL);await p.waitForFunction(()=>V18M.ready&&V22T.ready);await p.evaluate(()=>{ST.debugActive=true;startLevel();_UPDATE=()=>{};});
const ck=(name,pass,detail)=>{checks.push({name,pass,detail});};
const map=await p.evaluate(()=>{let gaps=0,unreachable=0,count=0;for(let lv=0;lv<7;lv++){cfg=LEVELS[lv];for(let n=0;n<30;n++){genMap();count++;const rocks=[],free=new Uint8Array(MAPW*MAPH),seen=new Uint8Array(free.length);for(let i=0;i<free.length;i++){if(terr.m[i]===5)rocks.push([i%MAPW,(i/MAPW)|0]);free[i]=!blockedAt(i%MAPW*TS+8,Math.floor(i/MAPW)*TS+8,10);}for(let i=0;i<rocks.length;i++)for(let j=i+1;j<rocks.length;j++)if(Math.hypot(Math.max(0,Math.abs(rocks[i][0]-rocks[j][0])-1)*TS,Math.max(0,Math.abs(rocks[i][1]-rocks[j][1])-1)*TS)<32)gaps++;const start=free.indexOf(1),q=[start];seen[start]=1;for(let h=0;h<q.length;h++){const i=q[h],x=i%MAPW,y=Math.floor(i/MAPW);for(const d of [-1,1,-MAPW,MAPW]){const j=i+d;if(j<0||j>=free.length||(d===1&&x===MAPW-1)||(d===-1&&x===0))continue;if(free[j]&&!seen[j]){seen[j]=1;q.push(j);}}}if(free.some((v,i)=>v&&!seen[i]))unreachable++;}}return{count,gaps,unreachable};});ck('210 maps have tank clearance and one connected free region',map.gaps===0&&map.unreachable===0,map);
const material=await p.evaluate(()=>HULL_KEYS.map(k=>{const a=V18M.ghostFrame(k,0,0,0),b=V18M.ghostFrame(k,0,0,Math.PI/2),da=a.getContext('2d').getImageData(0,0,128,128).data,db=b.getContext('2d').getImageData(0,0,128,128).data;let changed=0;for(let i=3;i<da.length;i+=4)if(da[i]!==db[i])changed++;return{k,changed,center:da[(64*128+64)*4+3],cache:V18M._gh.size};}));ck('three silhouettes include independently rotating turrets and solid deck',material.every(x=>x.changed>0&&(x.k==='heavy'?x.center===255:x.center>200)&&x.cache<=64),material);
const hold=await p.evaluate(()=>{RUN=RUN_DEF();RUN.pts=30;ST.state='upgrade';ST.upg={sel:0,from:'clear'};MENU=null;dispatchEvent(new KeyboardEvent('keydown',{code:'ArrowRight'}));for(let i=0;i<60;i++)tick(1/60);dispatchEvent(new KeyboardEvent('keyup',{code:'ArrowRight'}));const n=RUN.up.hp;for(let i=0;i<30;i++)tick(1/60);const release=RUN.up.hp===n;dispatchEvent(new KeyboardEvent('keydown',{code:'ArrowLeft'}));for(let i=0;i<60;i++)tick(1/60);dispatchEvent(new KeyboardEvent('keyup',{code:'ArrowLeft'}));return{n,release,remaining:RUN.up.hp,pts:RUN.pts};});ck('keyboard hold repeats, release stops, decrement refunds exactly',hold.n>=8&&hold.release&&hold.remaining===0&&hold.pts===30,hold);
const bound=await p.evaluate(()=>{RUN.up.cdr=21;RUN.pts=2;ST.upg.sel=4;dispatchEvent(new KeyboardEvent('keydown',{code:'ArrowRight'}));for(let i=0;i<120;i++)tick(1/60);dispatchEvent(new Event('blur'));const cap=RUN.up.cdr===21&&RUN.pts===2,stopped=!UPG_HOLD.key;return{cap,stopped};});ck('hold respects cap and blur cleanup',bound.cap&&bound.stopped,bound);
for(const k of ['assault','balanced','heavy']){await p.evaluate(k=>{RUN=RUN_DEF();RUN.hull=k;RUN.lvl=0;startLevel();G.visualScene('free');ST.state='play';MENU=null;SET.touch='off';setAimMode('manual');keys.clear();keys.add('KeyD');keys.add('ShiftLeft');for(let i=0;i<75;i++)tick(1/60);keys.clear();V15.queue.length=0;v15Player();window.ghostSample=V15.queue.filter(q=>q.kind==='ghost').map(q=>({alpha:q.alpha,ta:q.ta}));draw(0);},k);await p.screenshot({path:out+'/ghost-'+k+'.png'});const q=await p.evaluate(()=>ghostSample);ck(k+' trail is short, translucent and retains turret angle',q.length>0&&q.length<=4&&q.every(x=>x.alpha<=.25&&Number.isFinite(x.ta)),q);}
const fade=await p.evaluate(()=>{for(let i=0;i<40;i++)tick(1/60);return player.ghostA===0&&ghostCount()===0;});ck('dash release removes ghosts',fade);ck('no runtime errors',errors.length===0,errors);fs.writeFileSync(out+'/'+(process.env.RESULT_NAME||'fix-results.json'),JSON.stringify({checks,errors},null,2));console.log(checks.map(x=>[x.name,x.pass]));if(checks.some(c=>!c.pass))process.exitCode=1;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
