const fs=require('fs'),path=require('path'),pw=require('./runtime.cjs').pw;
const root=path.resolve(__dirname,'../..'),out=require('./runtime.cjs').output('fixes-20260905-heavy-loot');
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:require('./runtime.cjs').executablePath});const p=await b.newPage({viewport:{width:960,height:540}}),results=[],errors=[];p.on('pageerror',e=>errors.push(e.message));const check=(name,pass,detail)=>{results.push({name,pass,detail});console.log(pass?'PASS':'FAIL',name,JSON.stringify(detail));};try{
await p.goto(require('./runtime.cjs').gameURL);await p.waitForFunction(()=>V18M.ready&&V18UIR.ok('frame'));await p.evaluate(()=>{ST.debugActive=true;RUN=RUN_DEF();startLevel();ST.state='play';ST.spawnT=1e9;MENU=null;_UPDATE=()=>{};});
let r=await p.evaluate(()=>{if(!V18M.material)return null;return ['hull','turret'].map(part=>{const im=V18M.material('heavy',part),c=document.createElement('canvas');c.width=im.width;c.height=im.height;const g=c.getContext('2d');g.drawImage(im,0,0);const d=g.getImageData(0,0,c.width,c.height).data;let core=0,solid=0;const raw=V18M.imgs['heavy_'+part];g.clearRect(0,0,c.width,c.height);g.drawImage(raw,0,0);const src=g.getImageData(0,0,c.width,c.height).data;let transparentKept=true;for(let i=3;i<d.length;i+=4){if(src[i]>=32){core++;if(d[i]===255)solid++;}const pixel=(i-3)/4,x=pixel%c.width,y=Math.floor(pixel/c.width);if((x===0||y===0||x===c.width-1||y===c.height-1)&&d[i]!==0)transparentKept=false;}return{part,core,solid,transparentKept,deckSolid:part!=='hull'||d[(128*c.width+128)*4+3]===255,cached:im===V18M.material('heavy',part)};});});check('heavy hull and turret material is solid with transparent exterior',r&&r.every(x=>x.core>0&&x.solid===x.core&&x.transparentKept&&x.deckSolid&&x.cached),r);
r=await p.evaluate(()=>{RUN.hull='heavy';startLevel();ST.state='play';player.inv=1;ST.t=0;V15.queue.length=0;drawPlayer();return V15.queue.find(x=>x.kind==='player')?.alpha;});check('invulnerability preserves at least 90 percent body opacity',r>=.9,r);
r=await p.evaluate(()=>{RUN=RUN_DEF();startLevel();ST.state='play';player.hp=20;pickups=[{kind:'part',val:5,x:player.x+300,y:player.y,t:.001,bob:0},{kind:'eq',eqk:'armor',x:player.x+200,y:player.y,t:16,bob:0},{kind:'heal',x:player.x+100,y:player.y,t:16,bob:0}];levelClear();const first={pts:RUN.pts,eq:RUN.eq.armor,hp:player.hp,pending:pickups.length,x:pickups[0].x};for(let i=0;i<10;i++)tick(1/60);const moved=pickups[0].x<first.x;afterClear();afterClear();return{first,moved,pts:RUN.pts,eq:RUN.eq.armor,pending:pickups.length,state:ST.state};});check('clear grants distant loot before skip and animates recovery once',r.first.pts===5&&r.first.eq===1&&r.first.hp===36&&r.moved&&r.pts===5&&r.eq===1&&r.pending===0&&r.state==='upgrade',r);
r=await p.evaluate(()=>{RUN=RUN_DEF();RUN.lvl=LEVELS.length-1;startLevel();ST.state='play';pickups=[{kind:'part',val:7,x:player.x+900,y:player.y+600,t:16,bob:0}];levelClear();for(let i=0;i<260;i++)tick(1/60);return{pts:RUN.pts,state:ST.state,pending:pickups.length};});check('final level auto transition preserves all loot',r.pts===7&&r.state==='win'&&r.pending===0,r);
r=await p.evaluate(()=>{RUN=RUN_DEF();startLevel();ST.state='play';pickups=[{kind:'part',val:3,x:player.x,y:player.y,t:16,bob:0}];updPickups(.01);pickups.push({kind:'part',val:2,x:player.x+300,y:player.y,t:.001,bob:0});updPickups(.02);return{pts:RUN.pts,left:pickups.length};});check('normal play pickup and expiry behavior unchanged',r.pts===3&&r.left===0,r);
r=await p.evaluate(()=>{RUN=RUN_DEF();startLevel();ST.state='play';ST.debugActive=false;pickups=[{kind:'eq',eqk:'fire',x:player.x+300,y:player.y,t:16,bob:0}];levelClear();const save=JSON.parse(localStorage.getItem('trSave'));ST.debugActive=true;return{equipment:save.eq.fire};});check('clear rewards saved before closing game',r.equipment===1,r);
r=await p.evaluate(()=>{RUN=RUN_DEF();startLevel();ST.state='play';MENU=null;DBG.lab=false;ST.bossSpawned=true;ST.spawnT=1e9;ST.spawnedN=cfg.quota;enemies.length=0;pickups.length=0;spawnEnemyAt('tank',true,player.x+200,player.y);const e=enemies[0];applyDamage(e,99999,'shot');const expected={pts:pickups.filter(x=>x.kind==='part').reduce((n,x)=>n+x.val,0),eq:pickups.filter(x=>x.kind==='eq').length};tick(1/60);return{expected,state:ST.state,pts:RUN.pts,eq:Object.values(RUN.eq).reduce((a,b)=>a+b,0)};});check('actual last boss kill settles generated rewards',r.state==='clear'&&r.pts===r.expected.pts&&r.eq===r.expected.eq&&r.eq>0,r);
if(!process.env.BASELINE){for(const lvl of [0,3,4]){await p.evaluate(lvl=>{RUN=RUN_DEF();RUN.hull='heavy';RUN.lvl=lvl;startLevel();ST.state='play';MENU=null;player.inv=0;player.bodyA=-Math.PI/2;player.ta=-.5;draw(0);},lvl);await p.screenshot({path:out+'/heavy-'+lvl+'.png'});}await p.evaluate(()=>{ST.state='play';pickups=[{kind:'part',val:4,x:player.x+140,y:player.y+70,t:16,bob:0}];levelClear();tick(.1);draw(0);});await p.screenshot({path:out+'/clear-recovery.png'});}
check('no browser exceptions',errors.length===0,errors);fs.writeFileSync(out+'/'+(process.env.RESULT_NAME||'results.json'),JSON.stringify({results,errors},null,2));if(results.some(x=>!x.pass))process.exitCode=1;
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
