const fs=require('fs'),path=require('path'),pw=require('./runtime.cjs').pw;
const root=path.resolve(__dirname,'../..'),out=require('./runtime.cjs').output('ui-reference-20260905');
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:require('./runtime.cjs').executablePath});try{const p=await b.newPage({viewport:{width:960,height:540}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('./runtime.cjs').gameURL);await p.waitForFunction(()=>V22T.ready&&V18M.ready&&V18UIR.bg('title'));await p.evaluate(()=>{ST.debugActive=true;startLevel();toTitle();_UPDATE=()=>{};});
const check=(name,pass,detail)=>{checks.push({name,pass,detail});};
async function clickMenu(label){const q=await p.evaluate(label=>{draw(0);const i=menuItems(MENU.id).findIndex(x=>x.label===label),q=MENU_RECTS[i],r=cv.getBoundingClientRect();return{x:r.x+(q.x+q.w/2)*r.width/VW,y:r.y+(q.y+q.h/2)*r.height/VH};},label);await p.mouse.click(q.x,q.y);}
await clickMenu('mOpt');check('title settings hitbox',await p.evaluate(()=>MENU.id==='option'));await clickMenu('controls');check('settings controls hitbox',await p.evaluate(()=>MENU.id==='controls'));await p.keyboard.press('ArrowRight');await p.keyboard.press('Escape');check('keyboard back to settings',await p.evaluate(()=>MENU.id==='option'));
const layouts=await p.evaluate(()=>{const issues=[];for(const lang of ['zh','en','ja']){SET.lang=lang;for(const id of ['title','option','controls','padmap','pause','hull','wingman']){openMenu(id);draw(0);for(const q of MENU_RECTS)if(q.x<0||q.y<0||q.x+q.w>VW||q.y+q.h>VH)issues.push({lang,id,q:{x:q.x,y:q.y,w:q.w,h:q.h}});}}return issues;});check('all menu targets within canvas in three languages',layouts.length===0,layouts);
const atlas=await p.evaluate(()=>{const result=[];for(let i=0;i<7;i++){RUN.lvl=i;startLevel();const before=Array.from(terr.m);ST.state='play';MENU=null;draw(0);result.push({level:i,atlas:themeCfg().atlas,unchanged:before.every((v,k)=>terr.m[k]===v)});}return{ready:V22T.ready,sets:V22T.sets.length,draws:V22T.draws,result};});check('seven themes render without changing terrain collision ids',atlas.ready&&atlas.sets===8&&atlas.draws>0&&atlas.result.every(r=>r.unchanged),atlas);
const release=await p.evaluate(()=>{V18UIR.frame('play');return !V18UIR.bg('title')&&!V18UIR.bg('dep');});check('large menu images released in battle',release);
const touch=[];for(const [width,height]of [[568,320],[844,390],[960,432],[1280,720],[390,844]]){await p.setViewportSize({width,height});touch.push(await p.evaluate(()=>{SET.touch='on';setAimMode('hybrid');MENU=null;ST.state='play';updOvl();const a=[...document.querySelectorAll('.tbtn,#joy,#rjoy')].map(e=>({id:e.dataset.action||e.id,r:e.getBoundingClientRect()})).filter(e=>e.r.width>0),bad=[];for(let i=0;i<a.length;i++){const x=a[i];if(x.r.x<0||x.r.y<0||x.r.right>innerWidth||x.r.bottom>innerHeight)bad.push(x.id);for(let j=i+1;j<a.length;j++){const y=a[j];if(Math.min(x.r.right,y.r.right)>Math.max(x.r.left,y.r.left)+1&&Math.min(x.r.bottom,y.r.bottom)>Math.max(x.r.top,y.r.top)+1)bad.push(x.id+' / '+y.id);}}return{width:innerWidth,height:innerHeight,bad};}));}check('touch controls retain safe bounds and no overlaps',touch.every(r=>r.bad.length===0),touch);
check('no runtime errors',errors.length===0,errors);fs.writeFileSync(out+'/'+(process.env.RESULT_NAME||'regression.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify(checks));if(checks.some(c=>!c.pass))process.exitCode=1;
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
