const fs=require('fs'),path=require('path'),pw=require('./runtime.cjs').pw;const root=path.resolve(__dirname,'../..'),out=require('./runtime.cjs').output('combat-20260905');
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:require('./runtime.cjs').executablePath});try{const p=await b.newPage({viewport:{width:960,height:540}}),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('./runtime.cjs').gameURL);await p.waitForFunction(()=>V18M.ready&&V22T.ready);await p.evaluate(()=>{ST.debugActive=true;DBG.god=true;startLevel();MENU=null;ST.state='play';_UPDATE=()=>{};});const ck=(name,pass,detail)=>{checks.push({name,pass,detail});console.log(pass?'PASS':'FAIL',name);};
let r=await p.evaluate(()=>{const rows=[];for(let lv=0;lv<7;lv++)for(const form of ENCOUNTER_FORMS){RUN=RUN_DEF();RUN.lvl=lv;startLevel();const n=lv<3?3:6,ok=spawnFormation(n,form),units=enemies;rows.push({lv,form,ok,n:units.length,shared:units.every(e=>e.formation===units[0].formation),safe:units.every(e=>!blockedAt(e.x,e.y,13)&&units.every(o=>o===e||dist2(o.x,o.y,e.x,e.y)>24**2))});}return rows;});ck('21 formations share a group and spawn clear of terrain and each other',r.every(x=>x.ok&&x.shared&&x.safe),r);
r=await p.evaluate(()=>{const result=[];for(const k of ['assault','balanced','heavy']){RUN=RUN_DEF();RUN.hull=k;RUN.up.hp=5;RUN.up.atk=5;RUN.up.spd=5;RUN.up.def=3;startLevel();const s=calcStats();spawnAce();const e=enemies[0];result.push({k,hp:e.hp,wantHp:Math.round(s.maxHp*.8),spd:e.speed,wantSpd:s.speed*.8,atk:e.atk,wantAtk:s.atk*.8,shieldGap:e.shieldCooldown-e.shieldDur});}return result;});ck('three ace classes inherit 80 percent stats with shield downtime',r.every(x=>x.hp===x.wantHp&&x.spd===x.wantSpd&&x.atk===x.wantAtk&&x.shieldGap>=1),r);
r=await p.evaluate(()=>{RUN=RUN_DEF();RUN.hull='heavy';startLevel();spawnAce();const e=enemies[0];e.hp=e.maxHp=1000;e.def=.2;e.shieldT=1;const shield=applyDamage(e,100,'shot').dmg;e.shieldT=0;const open=applyDamage(e,100,'shot').dmg;return{shield,open};});ck('ace shield reduces damage but never grants permanent immunity',Math.abs(r.shield-16)<1e-9&&r.open===80,r);
r=await p.evaluate(()=>{RUN=RUN_DEF();RUN.hull='heavy';startLevel();spawnAce();const e=enemies[0];e.dashCd=0;e.shieldCd=0;shot(e.x+30,e.y,Math.PI,100,1,true,'mg');updateAce(e,.01);const warned=e.dashWind>0&&e.shieldWind>0;for(let i=0;i<50;i++)updateAce(e,.01);const active=e.dashT>0&&e.shieldT>0;for(let i=0;i<240;i++)updateAce(e,.01);return{warned,active,ended:e.shieldT===0&&e.dashT===0,shots:shots.filter(s=>!s.friendly).length};});ck('ace telegraphs before shield and dash, attacks and returns to cooldown',r.warned&&r.active&&r.ended&&r.shots>0,r);
r=await p.evaluate(()=>{RUN=RUN_DEF();startLevel();ST.state='play';ST.enc.regular=Math.floor((cfg.quota-2)/2);ST.enc.timer=0;shot(player.x,player.y,0,100,2,true,'mg');updateEncounter(.01);const cleared=shots.length===0;spawnAce();const wave=ST.enc.regular;for(let i=0;i<100;i++)updateEncounter(.1);const before=shots.length;updWingman(1);return{cleared,phase:ST.enc.phase,onlyAce:enemies.length===1&&enemies[0].elite,noSpawns:ST.enc.regular===wave,noWingShots:shots.length===before};});ck('mid-stage duel clears old shots, pauses waves and wingman fire',r.cleared&&r.phase==='duel'&&r.onlyAce&&r.noSpawns&&r.noWingShots,r);
r=await p.evaluate(()=>{const flows=[];for(let lv=0;lv<7;lv++){RUN=RUN_DEF();RUN.lvl=lv;startLevel();ST.state='play';MENU=null;DBG.lab=false;let aces=0,bosses=0,waves=0;const seen=new Set();for(let n=0;n<1000&&ST.state==='play';n++){ST.t+=.1;updEnemies(.1);waves=Math.max(waves,ST.enc.wave);for(const e of [...enemies]){if(seen.has(e.id))continue;seen.add(e.id);if(e.elite)aces++;if(e.boss)bosses++;applyDamage(e,100000,'shot');}shots.length=0;}flows.push({lv,state:ST.state,aces,bosses,waves,regular:ST.enc.regular,budget:cfg.quota-2});}return flows;});ck('all seven levels complete waves, exactly one mid-ace, then final boss',r.every(x=>x.state==='clear'&&x.aces===1&&x.bosses===1&&x.waves>=3&&x.regular===x.budget),r);
r=await p.evaluate(()=>{startLevel();const a=ST.enc;spawnAce();retryLevel();return{fresh:ST.enc!==a,phase:ST.enc.phase,regular:ST.enc.regular,enemies:enemies.length};});ck('retry resets all encounter state',r.fresh&&r.phase==='ready'&&r.regular===0&&r.enemies===0,r);
r=await p.evaluate(()=>{RUN=RUN_DEF();RUN.pts=30;ST.state='upgrade';MENU=null;ST.upg={sel:0,from:'clear'};PAD.hold.right=true;startUpgradeHold('hp',1,'pad','right');for(let i=0;i<60;i++)tickUpgradeHold(1/60);const n=RUN.up.hp;PAD.hold.right=false;tickUpgradeHold(.2);return{n,stopped:!UPG_HOLD.key};});ck('gamepad hold uses timed repeat and stops on release',r.n>=8&&r.stopped,r);
r=await p.evaluate(()=>{RUN=RUN_DEF();startLevel();ST.state='play';ST.enc.phase='ready';terr.m.fill(0);terr.m[10*MAPW+12]=5;player.x=12*TS-player.r;player.y=10*TS+8;wingman.x=player.x-10;wingman.y=player.y;wingman.vx=wingman.vy=0;updWingman(.001);return{safe:!blockedAt(player.x,player.y,player.r)};});ck('wingman contact cannot push player into solid cover',r.safe,r);
r=await p.evaluate(()=>{const rows=[];for(const form of ENCOUNTER_FORMS){RUN=RUN_DEF();RUN.lvl=0;startLevel();ST.state='play';MENU=null;spawnFormation(6,form);const first=enemies.map(e=>({x:e.x,y:e.y})),cost=[];for(let i=0;i<600;i++){const now=performance.now();ST.t+=1/60;updEnemies(1/60);updShots(1/60);if(i%3===0)draw(0);cost.push(performance.now()-now);}cost.sort((a,b)=>a-b);rows.push({form,finite:enemies.every(e=>Number.isFinite(e.x)&&Number.isFinite(e.y)&&Number.isFinite(e.hp)),moving:enemies.filter((e,i)=>first[i]&&Math.hypot(e.x-first[i].x,e.y-first[i].y)>50).length,p95ms:cost[Math.floor(cost.length*.95)]});}return rows;});ck('three formations advance during 600-step live combat without invalid state',r.every(x=>x.finite&&x.moving>=3),r);
r=await p.evaluate(()=>{for(const lang of ['zh','en','ja']){SET.lang=lang;openMenu('help','title');MENU.page=13;drawHelp();}SET.lang='zh';return HELP_PAGES===14;});ck('new encounter guide renders in all three languages',r);
for(const k of ['assault','balanced','heavy']){await p.evaluate(k=>{RUN=RUN_DEF();RUN.hull=k;RUN.lvl=3;startLevel();MENU=null;ST.state='play';SET.touch='off';spawnAce();const e=enemies[0];e.x=player.x+100;e.y=player.y-20;e.ox=e.x;e.oy=e.y;e.a=Math.PI;e.ta=Math.PI+.25;e.shieldT=1;e.shieldAge=.5;if(window.AIART)AIART.fx.length=0;draw(0);},k);await p.screenshot({path:out+'/ace-'+k+'.png'});}
for(const form of ['wedge','line','pincer']){await p.evaluate(form=>{RUN=RUN_DEF();RUN.lvl=3;startLevel();MENU=null;ST.state='play';spawnFormation(6,form);const g=ST.enc.group;cam.x=clamp(g.x-VW/2,0,WORLDW-VW);cam.y=clamp(g.y-VH/2,0,WORLDH-VH);cam.ox=cam.x;cam.oy=cam.y;if(window.AIART)AIART.fx.length=0;draw(0);},form);await p.screenshot({path:out+'/formation-'+form+'.png'});}
ck('no runtime exceptions',errors.length===0,errors);fs.writeFileSync(out+'/'+(process.env.RESULT_NAME||'encounter-results.json'),JSON.stringify({checks,errors},null,2));if(checks.some(c=>!c.pass))process.exitCode=1;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
