require('./runtime.cjs').output('audio-20260905');
const fs=require('fs'),pw=require('./runtime.cjs').pw;
(async()=>{const b=await pw.chromium.launch({headless:true,executablePath:require('./runtime.cjs').executablePath,args:['--autoplay-policy=no-user-gesture-required']});try{const p=await b.newPage(),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(require('./runtime.cjs').gameURL);await p.evaluate(()=>{initAudio();_UPDATE=()=>{};});await p.waitForTimeout(500);const ck=(name,pass,detail)=>checks.push({name,pass,detail});
const padPage=await b.newPage();await padPage.goto(require('./runtime.cjs').gameURL);await padPage.evaluate(()=>{_UPDATE=()=>{};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[{connected:true,axes:[.7,0,0,0],buttons:Array.from({length:17},()=>({pressed:false}))}]});pollPad();});await padPage.waitForTimeout(150);ck('gamepad-only first input initializes audio',await padPage.evaluate(()=>!!AC&&AC.state==='running'));await padPage.evaluate(async()=>{await AC.suspend();PAD.audioWakeAt=0;pollPad();});await padPage.waitForTimeout(150);ck('gamepad input restores suspended audio',await padPage.evaluate(()=>AC.state==='running'));await padPage.close();
let r=await p.evaluate(()=>{ST.t=500;sfxGate('probe',.1);newGame();return sfxGate('probe',.1);});ck('new game does not suppress SE from previous run',r);
await p.evaluate(async()=>{await AC.suspend();});await p.dispatchEvent('#touchovl','pointerdown',{pointerType:'touch',button:0});await p.waitForTimeout(200);r=await p.evaluate(()=>AC.state);ck('touch overlay resumes suspended audio',r==='running',r);
await p.evaluate(async()=>{await AC.resume();await AC.suspend();window.dispatchEvent(new Event('pageshow'));});await p.waitForTimeout(200);r=await p.evaluate(()=>AC.state);ck('return to page resumes audio',r==='running',r);
await p.evaluate(async()=>{await AC.resume();ST.muted=true;master.gain.value=0;newGame();initAudio();});r=await p.evaluate(()=>({muted:ST.muted,gain:master.gain.value}));ck('new game synchronizes master mute state',!r.muted&&r.gain===1,r);
await p.evaluate(async()=>{await AC.close();initAudio();});await p.waitForTimeout(500);r=await p.evaluate(()=>({state:AC.state,track:BGM.name}));ck('closed context recreates graph and music',r.state==='running'&&!!r.track,r);
// Measure actual mixed graph samples, not only whether nodes were constructed.
r=await p.evaluate(async()=>{if(AC.state!=='running')return {bgm:0,se:0};ST.muted=false;SET.bgm=3;SET.se=3;applyVolumes();master.gain.value=1;await BGM.play('stage1',true);const a=AC.createAnalyser();a.fftSize=2048;master.connect(a);const buf=new Float32Array(2048);const peak=()=>{a.getFloatTimeDomainData(buf);return Math.max(...buf.map(Math.abs));};await new Promise(r=>setTimeout(r,150));const bgm=peak();BGM.stop();SFX.cannon();await new Promise(r=>setTimeout(r,50));const se=peak();master.disconnect(a);a.disconnect();return{bgm,se};});ck('BGM and SE produce nonzero audio samples',r.bgm>.0001&&r.se>.0001,r);

r=await p.evaluate(async()=>{const get=BGM.get;let release;BGM.get=()=>new Promise(r=>release=r);const pending=BGM.play('stage1',true);BGM.stop();release(BGM.bufs.stage1);await pending;BGM.get=get;return !BGM.cur&&!BGM.wanted;});ck('stop invalidates pending decode',r);
r=await p.evaluate(async()=>{const get=BGM.get;BGM.get=async()=>{throw new Error('injected decode failure');};await BGM.play('stage1',true);const recorded=!!BGM.lastError;BGM.get=get;initAudio();await new Promise(r=>setTimeout(r,100));return recorded&&BGM.name==='stage1';});ck('failed decode retries on next recovery',r);
r=await p.evaluate(async()=>{await Promise.all([BGM.play('stage1',true),BGM.play('stage2',true),BGM.play('stage3',true)]);return BGM.name;});ck('rapid track switch keeps newest request',r==='stage3',r);
r=await p.evaluate(async()=>{SET.bgm=3;applyVolumes();duckMusic();SET.bgm=0;applyVolumes();await new Promise(r=>setTimeout(r,500));return bgmBus.gain.value;});ck('volume zero cancels old duck recovery automation',r===0,r);
ck('no unhandled errors',errors.length===0,errors);console.log(JSON.stringify(checks,null,2));fs.writeFileSync('output/audio-20260905/'+(process.env.RESULT||'results.json'),JSON.stringify(checks,null,2));if(checks.some(c=>!c.pass))process.exitCode=1;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
