#!/usr/bin/env python3
# Assemble baked renders + Kenney VFX into src/data/assets.data.js (base64 manifest)
import os, json, base64, io, math
from PIL import Image, ImageDraw, ImageFilter

ROOT = "/Volumes/vol1/像素小游戏"
REN = f"{ROOT}/art-pipeline/renders"
TANK_DIR = f"{REN}/IRONCLAD"
SCENE_DIR = f"{REN}/scene"
VFX_SRC = f"{ROOT}/art-pipeline/assets/vfx/kenney_particle_pack/PNG (Transparent)"
OUT_JS = f"{ROOT}/src/data/assets.data.js"
FRAMES, FW = 16, 160

images, man = {}, {"tank": {}, "scene": {}, "vfx": {}}

def b64img(im, optimize=True):
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=optimize)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()

def strip(prefix):
    frames = [Image.open(f"{TANK_DIR}/{prefix}_{i+1:04d}.png").convert("RGBA") for i in range(FRAMES)]
    sheet = Image.new("RGBA", (FW*FRAMES, FW))
    for i, f in enumerate(frames): sheet.paste(f, (i*FW, 0))
    return sheet

# ---- tank strips ----
for p in ("hull_diff", "hull_norm", "hull_emis", "tur_diff", "tur_norm", "tur_emis", "shadow"):
    s = strip(p)
    key = p.replace("_", "")
    images[key] = b64img(s)
    print(f"strip {key}: {len(images[key])//1024}KB")

# anchor: x=帧中心(坦克几何居中), y=阴影质心(地面接触点)
sh = Image.open(f"{TANK_DIR}/shadow_0001.png").convert("RGBA")
a = sh.split()[3]
bbox = a.getbbox()
hist = a.histogram()
tot = sum(hist)
cy = sum(i * v for i, v in enumerate(hist)) / tot
px = a.load()
W, H = a.size
sx = sy = cnt = 0
for y in range(H):
    for x in range(W):
        v = px[x, y]
        if v > 8: sx += x; sy += y; cnt += 1
man["tank"] = {"frames": FRAMES, "fw": FW, "fh": FW,
               "anchor": [FW / 2, round(sy/cnt, 1)],
               "shadowBBox": list(bbox) if bbox else [40, 60, 120, 120]}
print("anchor", man["tank"]["anchor"])

# ---- scene ----
meta = json.load(open(f"{SCENE_DIR}/scene_meta.json"))
S = meta["ortho_scale"]; RESX, RESY = meta["res"]; ELEV = meta["elev"]
ppu = RESY / S                      # screen px per world unit
cosE, sinE = math.cos(math.radians(ELEV)), math.sin(math.radians(ELEV))
g = ground_img = Image.open(f"{SCENE_DIR}/ground.png").convert("RGB")
images["ground"] = b64img(ground_img)
man["scene"] = {"w": RESX//2, "h": RESY//2, "rect": [0, 0, RESX//2, RESY//2], "props": []}
# tank frame draw width so tank length matches scene scale:
# bake ppu_tank = 160/22.05 ; scene game-px per unit = ppu*0.5 ; drawW = 160 * (ppu*0.5)/(160/22.05)
draww = 160 * (ppu*0.5) / (160/22.05)
draww = max(44, min(120, round(draww)))
man["tank"]["draw"] = draww
man["tank"]["sceneScale"] = {"ppu": round(ppu, 3), "draww": draww}
print("scene ppu", round(ppu,2), "tank draww", draww)

for p in meta["props"]:
    im = Image.open(f"{SCENE_DIR}/{p['img']}").convert("RGBA")
    bb = im.split()[3].getbbox()
    if not bb: continue
    key = "p_" + p["name"]
    images[key] = b64img(im.crop(bb))
    # y-sort 键 = 精灵底边在画面中的 game y (视觉精确, 免去 3D 投影换算)
    by = (bb[1] + bb[3]) * 0.5
    man["scene"]["props"].append({"k": key, "by": round(by, 1),
                                  "c": list(bb), "z": p["zmax"], "s": 0.5})
man["scene"]["props"].sort(key=lambda q: q["by"])
print("props:", len(man["scene"]["props"]))

# ---- vfx textures ----
def pick(cands, size):
    for c in cands:
        p = f"{VFX_SRC}/{c}"
        if os.path.exists(p):
            im = Image.open(p).convert("RGBA")
            im.thumbnail((size, size), Image.LANCZOS)
            return im
    return None

vfx = {
    "flash": pick(["muzzle_02.png", "muzzle_01.png"], 48),
    "fire": pick(["flame_01.png", "fire_01.png", "flame_02.png"], 56),
    "smoke": pick(["smoke_03.png", "smoke_01.png"], 52),
    "spark": pick(["spark_01.png", "spark_02.png"], 24),
    "scorch": pick(["scorch_02.png", "scorch_01.png"], 72),
}
# soft ring generated (texture asset, not runtime-drawn)
ring = Image.new("RGBA", (96, 96))
d = ImageDraw.Draw(ring)
d.ellipse([8, 8, 88, 88], outline=(255, 255, 255, 255), width=7)
ring = ring.filter(ImageFilter.GaussianBlur(2.2))
vfx["ring"] = ring

# Kenney 粒子是白色蒙版, 组装时烘焙颜色 (运行时 additive/alpha 直接可用)
TINT = {"flash": (1.0, 0.93, 0.72), "fire": (1.0, 0.52, 0.14), "smoke": (0.30, 0.30, 0.33),
        "spark": (1.0, 0.85, 0.45), "scorch": (0.16, 0.14, 0.13), "ring": (1.0, 0.9, 0.7)}
for k, im in vfx.items():
    if im is None: print("MISSING VFX", k); continue
    im = im.copy()
    r, g, b, a = im.split()
    r = r.point(lambda v: int(v * TINT[k][0]))
    g = g.point(lambda v: int(v * TINT[k][1]))
    b = b.point(lambda v: int(v * TINT[k][2]))
    images["fx_" + k] = b64img(Image.merge("RGBA", (r, g, b, a)))
    man["vfx"][k] = "fx_" + k

# ---- write JS ----
total = sum(len(v) for v in images.values())
js = "/* generated by art-pipeline/scripts/assemble_assets.py — CC0 baked assets */\n"
js += "window.ASSET_MANIFEST=" + json.dumps({"images": images, "tank": man["tank"],
                                              "scene": man["scene"], "vfx": man["vfx"]},
                                             separators=(",", ":")) + ";\n"
open(OUT_JS, "w").write(js)
print(f"WROTE {OUT_JS} images={len(images)} total={total//1024}KB js={len(js)//1024}KB")
