#!/usr/bin/env python3
"""Inline reviewed-at-runtime mecha PNGs for the single-file build."""

import base64
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "assets" / "ai-v18-mecha"
OUT = ROOT / "src" / "data" / "v18_mecha.data.js"


def main() -> None:
    manifest = json.loads((PKG / "manifest.json").read_text(encoding="utf-8"))
    units = {}
    total = 0
    for key, spec in manifest["units"].items():
        hull = PKG / spec["hullRuntime"]
        turret = PKG / spec["turretRuntime"]
        for path, digest in ((hull, spec["sha256"]["hullRuntime"]),
                             (turret, spec["sha256"]["turretRuntime"])):
            data = path.read_bytes()
            got = hashlib.sha256(data).hexdigest()
            if got != digest:
                raise SystemExit(f"SHA-256 mismatch for {path}: got {got}, expected {digest}")
            total += len(data)
        units[key] = {
            "hull": "data:image/png;base64," + base64.b64encode(hull.read_bytes()).decode(),
            "turret": "data:image/png;base64," + base64.b64encode(turret.read_bytes()).decode(),
            "frameAnglesDeg": spec["frameAnglesDeg"],
            "cellSize": manifest["architecture"]["hull"]["cellSize"],
            "pivotPx": manifest["architecture"]["hull"]["pivotPx"],
            "turretPivotPx": manifest["architecture"]["turret"]["pivotPx"],
        }
    payload = {"schema": manifest["schema"], "status": manifest["status"], "units": units}
    OUT.write_text(
        '"use strict";\n'
        "/* Generated by tools/assemble_v18_mecha_data.py; runtime PNGs only. */\n"
        "window.V18MECHA=" + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"v18_mecha.data.js: {len(units)} units, {total / 1024:.0f} KB raw")


if __name__ == "__main__":
    main()
