/* Reproducible image embedding; original generated PNGs remain in assets. */
const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const read=n=>'data:image/jpeg;base64,'+fs.readFileSync(path.join(root,'assets/ai-v22-ui',n+'.jpg')).toString('base64');
const data={title:read('title-daylight'),terrain:read('terrain-daylight')};
if(fs.existsSync(path.join(root,'assets/ai-v22-ui/depot-daylight.jpg')))data.dep=read('depot-daylight');
fs.writeFileSync(path.join(root,'src/data/v22_art.data.js'),'"use strict";\n// Generated by tools/assemble_v22_art.js\nwindow.V22ART='+JSON.stringify(data)+';\nV18UI.images.title=V22ART.title;\nif(V22ART.dep)V18UI.images.dep=V22ART.dep;\n');
console.log('Embedded daylight assets',Object.keys(data));
