plugins {
    id 'com.android.application'
}

def keystorePropsFile = rootProject.file("keystore/keystore.properties")
def keystoreProps = new Properties()
if (keystorePropsFile.exists()) {
    keystoreProps.load(new FileInputStream(keystorePropsFile))
}

android {
    namespace 'com.rance.steelroar'
    compileSdk 35

    defaultConfig {
        applicationId "com.rance.steelroar"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    if (keystorePropsFile.exists()) {
        signingConfigs {
            release {
                storeFile rootProject.file("keystore/" + keystoreProps['storeFile'])
                storePassword keystoreProps['storePassword']
                keyAlias keystoreProps['keyAlias']
                keyPassword keystoreProps['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (keystorePropsFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
    }
}
